#!/bin/bash

# remove wine extensions
rm -f ~/.local/share/applications/wine-extension*.desktop
rm -f ~/.local/share/icons/hicolor/*/*/application-x-wine-extension*

# remove old cache
rm -f ~/.local/share/applications/mimeinfo.cache
rm -f ~/.local/share/mime/packages/x-wine*
rm -f ~/.local/share/mime/application/x-wine-extension*

# update cache
update-desktop-database ~/.local/share/applications
update-mime-database ~/.local/share/mime/
